# Generated by Django 4.2.4 on 2023-09-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_branch_district_delete_city_delete_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
    ]
